services:
  valheim:
    image: mbround18/valheim:latest
    container_name: valheim-server
    restart: unless-stopped
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      PORT: 2456
      NAME: 'Helixar'
      WORLD: 'ourworld'
      PASSWORD: 'Valhalla'
      PUBLIC: '1'
      TYPE: 'BepInEx'
      TZ: 'Asia/Manila'
      UPDATE_ON_STARTUP: 0
      AUTO_UPDATE: 0
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: '* */60 * * *'
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
